### ISSUE TITLE
wrong precision returned in after PR #13

### ISSUE THREAD

**Issue by sirpy** [Mean-Finance/uniswap-v3-oracle#15]
The oracle returns a number that's missing 4 decimals.
you can check it on celoscan:
New Oracle: https://celoscan.io/address/0x00851A91a3c4E9a4c1B48df827Bacc1f884bdE28#readContract
result: 48163752414700
Old Oracle: https://celoscan.io/address/0x8a45f1E50e46d116aAB5d294F9191f8fc2E636c0#readContract
result: 481637524147005886

input:
_baseAmount (uint128)
100000000000000
_baseToken (address)
0x471ece3750da237f93b8e339c536989b8978a438
_quoteToken (address)
0x765de816845861e75a25fca122bb6898b8b1282a
_period (uint32)
600

**Comment by 0xsambugs** [comment]
Thanks for pointing this out @sirpy ! @wei3erHase and I will take a look asap to understand what could be happening 🫡

**Comment by sirpy** [comment]
@wei3erHase I dono super strange... it now seems fine.
could it be related to observation or something? i'm 100% sure that it returned different values.

**Comment by wei3erHase** [comment]
mhmm i'd say perhaps an error when writing down the base amount...
notice: `100000000000000 = 0.0001e18`
